# 开发环境配置
admin:
  prefix: '/basic-api'
  port: 9000
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: 'F:\Tools\img'
    # 文件服务器地址，开发环境
    domain: 'http://localhost:9000'
    # 文件虚拟路径, 必须以 / 开头， 如 http://localhost:9000/static/****.jpg  , 如果不需要则 设置 ''
    serveRoot: '/static'
# 数据库配置
db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: '123456'
    database: 'zj_db_system'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: false
    multipleStatements: true
    dropSchema: false
    synchronize: false
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: 'localhost'
  port: 6379
  db: 0
  keyPrefix: 'nest:'

# 权限 白名单配置
perm:
  router:
    whitelist: [{ path: '/basic-api/auth/login', method: 'POST'  }, { path: '/basic-api/auth/logout', method: 'GET' }, { path: '/basic-api/auth/authcode', method: 'GET' },{ path: '/basic-api/upload/', method: 'GET' }]

# 用户相关
# 初始密码， 重置密码
user:
  initialPassword: 'jxxqz123'
