 # 线上 Vercel 生产环境配置（已修复所有坑）
admin:
  prefix: '/basic-api'
  port: ${PORT}          # 这里必须改！Vercel 自动分配端口
  logger:
    dir: '../logs'
  file:
    location: '../upload'
    domain: 'https://nest-api-client-pre.vercel.app'  # 你的线上域名
    serveRoot: '/static'

# 数据库配置（你的 Supabase 没问题，保留）
db:
  postgres:
    host: 'db.usaunarzresehtjqgzce.supabase.co'
    username: 'postgres'
    password: 'SyerIYosUwSjsWJK'
    database: 'postgres'
    port: 5432
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: false
    multipleStatements: true
    dropSchema: false
    synchronize: true
    ssl: true
    extra:
      ssl:
        rejectUnauthorized: false

# --------------------------
# Redis 必须注释！！！
# Vercel 没有本地 Redis，开启会直接启动失败
# --------------------------
# redis:
#   host: 'localhost'
#   port: 6379
#   db: 0
#   keyPrefix: 'nest:'

# 权限白名单（不变）
perm:
  router:
    whitelist: [
      { path: '/basic-api/auth/login', method: 'POST' },
      { path: '/basic-api/auth/logout', method: 'GET' },
      { path: '/basic-api/auth/authcode', method: 'GET' }
    ]

# 用户默认密码（不变）
user:
  initialPassword: 'jxxqz123'